

import DrawingUI

public struct WebColor: CaseIterable {
    
    // MARK: Implements CaseIterable
    
    public static var allCases: Self.AllCases {
        WebColorNameItem.allCases.map {
            WebColor(item: $0)
        }
    }
    
    // MARK: Implements WebColor
    
    public let item: WebColorNameItem
    
    public var name: String {
        item.rawValue
    }
    
    public var hexString: String {
        item.hexString
    }
    /// Updates a `Routine.AlarmRoutine`
    ///
    /// Writes the alarm to our backend using an `HTTP` API (which returns a `dataVersion`),
    /// then confirms that `dataVersion` makes it into the shadow.
    ///
    /// - Important: This implementation takes a different approach to ensuring that `dataVersion`
    /// makes it to the shadow. The norm is to watch shadow changes over `MQTT`, falling back to and `HTTP` endpoint
    /// after some time. That approach cannot be used in this situation: The app cannot receive `MQTT` updates while the
    /// app state is`UIState.background`.
    public var rgbTuple: (red: Int, green: Int, blue: Int) {
        let hexStringValue = hexString.hexStringValue
        let mask: UInt32 = 0x000000FF
        let r = (hexStringValue >> 16) & mask
        let g = (hexStringValue >> 8) & mask
        let b = (hexStringValue >> 0) & mask
        return (Int(r), Int(g), Int(b))
    }

    public var rgb: [Int] {
        let rgbTuple = self.rgbTuple
        return [
            Int(rgbTuple.red),
            Int(rgbTuple.green),
            Int(rgbTuple.blue)
        ]
    }

    
    // R, G, B value in the range of 0x00 - 0xFF
    public var rgb8Bit: [UInt8] {
        let rgbTuple = self.rgbTuple
        return [
            UInt8(rgbTuple.red),
            UInt8(rgbTuple.green),
            UInt8(rgbTuple.blue)
        ]
    }
}

public enum WebColorNameItem: String, CaseIterable {
    
    case basicWhite = "White"
    case basicSilver = "Silver"
    case basicGray = "Gray"
    case basicBlack = "Black"
    case basicRed = "Red"
    case basicMaroon = "Maroon"
    case basicYellow = "Yellow"
    case basicOlive = "Olive"
    case basicLime = "Lime"
    case basicGreen = "Green"
    case basicAqua = "Aqua"
    case basicTeal = "Teal"
    case basicBlue = "Blue"
    case basicNavy = "Navy"
    case basicFuchsia = "Fuchsia"
    case basicPurple = "Purple"
    
    case airForceBlueRaf = "Air Force Blue (Raf)"
    case airForceBlueUsaf = "Air Force Blue (Usaf)"
    case airSuperiorityBlue = "Air Superiority Blue"
    case alabamaCrimson = "Alabama Crimson"
    case aliceBlue = "Alice Blue"
    case alizarinCrimson = "Alizarin Crimson"
    case alloyOrange = "Alloy Orange"
    case almond = "Almond"
    case amaranth = "Amaranth"
    case amber = "Amber"
    case amberSaeEce = "Amber (Sae/Ece)"
    case americanRose = "American Rose"
    case amethyst = "Amethyst"
    case androidGreen = "Android Green"
    case antiFlashWhite = "Anti-Flash White"
    case antiqueBrass = "Antique Brass"
    case antiqueFuchsia = "Antique Fuchsia"
    case antiqueRuby = "Antique Ruby"
    case antiqueWhite = "Antique White"
    case aoEnglish = "Ao (English)"
    case appleGreen = "Apple Green"
    case apricot = "Apricot"
//    case aqua = "Aqua"
    case aquamarine = "Aquamarine"
    case armyGreen = "Army Green"
    case arsenic = "Arsenic"
    case arylideYellow = "Arylide Yellow"
    case ashGrey = "Ash Grey"
    case asparagus = "Asparagus"
    case atomicTangerine = "Atomic Tangerine"
    case auburn = "Auburn"
    case aureolin = "Aureolin"
    case aurometalsaurus = "Aurometalsaurus"
    case avocado = "Avocado"
    case azure = "Azure"
    case azureMistWeb = "Azure Mist/Web"
    case babyBlue = "Baby Blue"
    case babyBlueEyes = "Baby Blue Eyes"
    case babyPink = "Baby Pink"
    case ballBlue = "Ball Blue"
    case bananaMania = "Banana Mania"
    case bananaYellow = "Banana Yellow"
    case barnRed = "Barn Red"
    case battleshipGrey = "Battleship Grey"
    case bazaar = "Bazaar"
    case beauBlue = "Beau Blue"
    case beaver = "Beaver"
    case beige = "Beige"
    case bigDipORuby = "Big Dip O’Ruby"
    case bisque = "Bisque"
    case bistre = "Bistre"
    case bittersweet = "Bittersweet"
    case bittersweetShimmer = "Bittersweet Shimmer"
//    case black = "Black"
    case blackBean = "Black Bean"
    case blackLeatherJacket = "Black Leather Jacket"
    case blackOlive = "Black Olive"
    case blanchedAlmond = "Blanched Almond"
    case blastOffBronze = "Blast-Off Bronze"
    case bleuDeFrance = "Bleu De France"
    case blizzardBlue = "Blizzard Blue"
    case blond = "Blond"
//    case blue = "Blue"
    case blueBell = "Blue Bell"
    case blueCrayola = "Blue (Crayola)"
    case blueGray = "Blue Gray"
    case blueGreen = "Blue-Green"
    case blueMunsell = "Blue (Munsell)"
    case blueNcs = "Blue (Ncs)"
    case bluePigment = "Blue (Pigment)"
    case blueRyb = "Blue (Ryb)"
    case blueSapphire = "Blue Sapphire"
    case blueViolet = "Blue-Violet"
    case blush = "Blush"
    case bole = "Bole"
    case bondiBlue = "Bondi Blue"
    case bone = "Bone"
    case bostonUniversityRed = "Boston University Red"
    case bottleGreen = "Bottle Green"
    case boysenberry = "Boysenberry"
    case brandeisBlue = "Brandeis Blue"
    case brass = "Brass"
    case brickRed = "Brick Red"
    case brightCerulean = "Bright Cerulean"
    case brightGreen = "Bright Green"
    case brightLavender = "Bright Lavender"
    case brightMaroon = "Bright Maroon"
    case brightPink = "Bright Pink"
    case brightTurquoise = "Bright Turquoise"
    case brightUbe = "Bright Ube"
    case brilliantLavender = "Brilliant Lavender"
    case brilliantRose = "Brilliant Rose"
    case brinkPink = "Brink Pink"
    case britishRacingGreen = "British Racing Green"
    case bronze = "Bronze"
    case brownTraditional = "Brown (Traditional)"
    case brownWeb = "Brown (Web)"
    case bubbleGum = "Bubble Gum"
    case bubbles = "Bubbles"
    case buff = "Buff"
    case bulgarianRose = "Bulgarian Rose"
    case burgundy = "Burgundy"
    case burlywood = "Burlywood"
    case burntOrange = "Burnt Orange"
    case burntSienna = "Burnt Sienna"
    case burntUmber = "Burnt Umber"
    case byzantine = "Byzantine"
    case byzantium = "Byzantium"
    case cadet = "Cadet"
    case cadetBlue = "Cadet Blue"
    case cadetGrey = "Cadet Grey"
    case cadmiumGreen = "Cadmium Green"
    case cadmiumOrange = "Cadmium Orange"
    case cadmiumRed = "Cadmium Red"
    case cadmiumYellow = "Cadmium Yellow"
    case cafAuLait = "Café Au Lait"
    case cafNoir = "Café Noir"
    case calPolyGreen = "Cal Poly Green"
    case cambridgeBlue = "Cambridge Blue"
    case camel = "Camel"
    case cameoPink = "Cameo Pink"
    case camouflageGreen = "Camouflage Green"
    case canaryYellow = "Canary Yellow"
    case candyAppleRed = "Candy Apple Red"
    case candyPink = "Candy Pink"
    case capri = "Capri"
    case caputMortuum = "Caput Mortuum"
    case cardinal = "Cardinal"
    case caribbeanGreen = "Caribbean Green"
    case carmine = "Carmine"
    case carmineMP = "Carmine (M&P)"
    case carminePink = "Carmine Pink"
    case carmineRed = "Carmine Red"
    case carnationPink = "Carnation Pink"
    case carnelian = "Carnelian"
    case carolinaBlue = "Carolina Blue"
    case carrotOrange = "Carrot Orange"
    case catalinaBlue = "Catalina Blue"
    case ceil = "Ceil"
    case celadon = "Celadon"
    case celadonBlue = "Celadon Blue"
    case celadonGreen = "Celadon Green"
    case celesteColour = "Celeste (Colour)"
    case celestialBlue = "Celestial Blue"
    case cerise = "Cerise"
    case cerisePink = "Cerise Pink"
    case cerulean = "Cerulean"
    case ceruleanBlue = "Cerulean Blue"
    case ceruleanFrost = "Cerulean Frost"
    case cgBlue = "Cg Blue"
    case cgRed = "Cg Red"
    case chamoisee = "Chamoisee"
    case champagne = "Champagne"
    case charcoal = "Charcoal"
    case charmPink = "Charm Pink"
    case chartreuseTraditional = "Chartreuse (Traditional)"
    case chartreuseWeb = "Chartreuse (Web)"
    case cherry = "Cherry"
    case cherryBlossomPink = "Cherry Blossom Pink"
    case chestnut = "Chestnut"
    case chinaPink = "China Pink"
    case chinaRose = "China Rose"
    case chineseRed = "Chinese Red"
    case chocolateTraditional = "Chocolate (Traditional)"
    case chocolateWeb = "Chocolate (Web)"
    case chromeYellow = "Chrome Yellow"
    case cinereous = "Cinereous"
    case cinnabar = "Cinnabar"
    case cinnamon = "Cinnamon"
    case citrine = "Citrine"
    case classicRose = "Classic Rose"
    case cobalt = "Cobalt"
    case cocoaBrown = "Cocoa Brown"
    case coffee = "Coffee"
    case columbiaBlue = "Columbia Blue"
    case congoPink = "Congo Pink"
    case coolBlack = "Cool Black"
    case coolGrey = "Cool Grey"
    case copper = "Copper"
    case copperCrayola = "Copper (Crayola)"
    case copperPenny = "Copper Penny"
    case copperRed = "Copper Red"
    case copperRose = "Copper Rose"
    case coquelicot = "Coquelicot"
    case coral = "Coral"
    case coralPink = "Coral Pink"
    case coralRed = "Coral Red"
    case cordovan = "Cordovan"
    case corn = "Corn"
    case cornellRed = "Cornell Red"
    case cornflowerBlue = "Cornflower Blue"
    case cornsilk = "Cornsilk"
    case cosmicLatte = "Cosmic Latte"
    case cottonCandy = "Cotton Candy"
    case cream = "Cream"
    case crimson = "Crimson"
    case crimsonGlory = "Crimson Glory"
    case cyan = "Cyan"
    case cyanProcess = "Cyan (Process)"
    case daffodil = "Daffodil"
    case dandelion = "Dandelion"
    case darkBlue = "Dark Blue"
    case darkBrown = "Dark Brown"
    case darkByzantium = "Dark Byzantium"
    case darkCandyAppleRed = "Dark Candy Apple Red"
    case darkCerulean = "Dark Cerulean"
    case darkChestnut = "Dark Chestnut"
    case darkCoral = "Dark Coral"
    case darkCyan = "Dark Cyan"
    case darkElectricBlue = "Dark Electric Blue"
    case darkGoldenrod = "Dark Goldenrod"
    case darkGray = "Dark Gray"
    case darkGreen = "Dark Green"
    case darkImperialBlue = "Dark Imperial Blue"
    case darkJungleGreen = "Dark Jungle Green"
    case darkKhaki = "Dark Khaki"
    case darkLava = "Dark Lava"
    case darkLavender = "Dark Lavender"
    case darkMagenta = "Dark Magenta"
    case darkMidnightBlue = "Dark Midnight Blue"
    case darkOliveGreen = "Dark Olive Green"
    case darkOrange = "Dark Orange"
    case darkOrchid = "Dark Orchid"
    case darkPastelBlue = "Dark Pastel Blue"
    case darkPastelGreen = "Dark Pastel Green"
    case darkPastelPurple = "Dark Pastel Purple"
    case darkPastelRed = "Dark Pastel Red"
    case darkPink = "Dark Pink"
    case darkPowderBlue = "Dark Powder Blue"
    case darkRaspberry = "Dark Raspberry"
    case darkRed = "Dark Red"
    case darkSalmon = "Dark Salmon"
    case darkScarlet = "Dark Scarlet"
    case darkSeaGreen = "Dark Sea Green"
    case darkSienna = "Dark Sienna"
    case darkSlateBlue = "Dark Slate Blue"
    case darkSlateGray = "Dark Slate Gray"
    case darkSpringGreen = "Dark Spring Green"
    case darkTan = "Dark Tan"
    case darkTangerine = "Dark Tangerine"
    case darkTaupe = "Dark Taupe"
    case darkTerraCotta = "Dark Terra Cotta"
    case darkTurquoise = "Dark Turquoise"
    case darkViolet = "Dark Violet"
    case darkYellow = "Dark Yellow"
    case dartmouthGreen = "Dartmouth Green"
    case davySGrey = "Davy'S Grey"
    case debianRed = "Debian Red"
    case deepCarmine = "Deep Carmine"
    case deepCarminePink = "Deep Carmine Pink"
    case deepCarrotOrange = "Deep Carrot Orange"
    case deepCerise = "Deep Cerise"
    case deepChampagne = "Deep Champagne"
    case deepChestnut = "Deep Chestnut"
    case deepCoffee = "Deep Coffee"
    case deepFuchsia = "Deep Fuchsia"
    case deepJungleGreen = "Deep Jungle Green"
    case deepLilac = "Deep Lilac"
    case deepMagenta = "Deep Magenta"
    case deepPeach = "Deep Peach"
    case deepPink = "Deep Pink"
    case deepRuby = "Deep Ruby"
    case deepSaffron = "Deep Saffron"
    case deepSkyBlue = "Deep Sky Blue"
    case deepTuscanRed = "Deep Tuscan Red"
    case denim = "Denim"
    case desert = "Desert"
    case desertSand = "Desert Sand"
    case dimGray = "Dim Gray"
    case dodgerBlue = "Dodger Blue"
    case dogwoodRose = "Dogwood Rose"
    case dollarBill = "Dollar Bill"
    case drab = "Drab"
    case dukeBlue = "Duke Blue"
    case earthYellow = "Earth Yellow"
    case ebony = "Ebony"
    case ecru = "Ecru"
    case eggplant = "Eggplant"
    case eggshell = "Eggshell"
    case egyptianBlue = "Egyptian Blue"
    case electricBlue = "Electric Blue"
    case electricCrimson = "Electric Crimson"
    case electricCyan = "Electric Cyan"
    case electricGreen = "Electric Green"
    case electricIndigo = "Electric Indigo"
    case electricLavender = "Electric Lavender"
    case electricLime = "Electric Lime"
    case electricPurple = "Electric Purple"
    case electricUltramarine = "Electric Ultramarine"
    case electricViolet = "Electric Violet"
    case electricYellow = "Electric Yellow"
    case emerald = "Emerald"
    case englishLavender = "English Lavender"
    case etonBlue = "Eton Blue"
    case fallow = "Fallow"
    case faluRed = "Falu Red"
    case fandango = "Fandango"
    case fashionFuchsia = "Fashion Fuchsia"
    case fawn = "Fawn"
    case feldgrau = "Feldgrau"
    case fernGreen = "Fern Green"
    case ferrariRed = "Ferrari Red"
    case fieldDrab = "Field Drab"
    case fireEngineRed = "Fire Engine Red"
    case firebrick = "Firebrick"
    case flame = "Flame"
    case flamingoPink = "Flamingo Pink"
    case flavescent = "Flavescent"
    case flax = "Flax"
    case floralWhite = "Floral White"
    case fluorescentOrange = "Fluorescent Orange"
    case fluorescentPink = "Fluorescent Pink"
    case fluorescentYellow = "Fluorescent Yellow"
    case folly = "Folly"
    case forestGreenTraditional = "Forest Green (Traditional)"
    case forestGreenWeb = "Forest Green (Web)"
    case frenchBeige = "French Beige"
    case frenchBlue = "French Blue"
    case frenchLilac = "French Lilac"
    case frenchLime = "French Lime"
    case frenchRaspberry = "French Raspberry"
    case frenchRose = "French Rose"
//    case fuchsia = "Fuchsia"
    case fuchsiaCrayola = "Fuchsia (Crayola)"
    case fuchsiaPink = "Fuchsia Pink"
    case fuchsiaRose = "Fuchsia Rose"
    case fulvous = "Fulvous"
    case fuzzyWuzzy = "Fuzzy Wuzzy"
    case gainsboro = "Gainsboro"
    case gamboge = "Gamboge"
    case ghostWhite = "Ghost White"
    case ginger = "Ginger"
    case glaucous = "Glaucous"
    case glitter = "Glitter"
    case goldMetallic = "Gold (Metallic)"
    case goldWebGolden = "Gold (Web) (Golden)"
    case goldenBrown = "Golden Brown"
    case goldenPoppy = "Golden Poppy"
    case goldenYellow = "Golden Yellow"
    case goldenrod = "Goldenrod"
    case grannySmithApple = "Granny Smith Apple"
//    case gray = "Gray"
    case grayAsparagus = "Gray-Asparagus"
    case grayHtmlCssGray = "Gray (Html/Css Gray)"
    case grayX11Gray = "Gray (X11 Gray)"
    case greenColorWheelX11Green = "Green (Color Wheel) (X11 Green)"
    case greenCrayola = "Green (Crayola)"
    case greenHtmlCssGreen = "Green (Html/Css Green)"
    case greenMunsell = "Green (Munsell)"
    case greenNcs = "Green (Ncs)"
    case greenPigment = "Green (Pigment)"
    case greenRyb = "Green (Ryb)"
    case greenYellow = "Green-Yellow"
    case grullo = "Grullo"
    case guppieGreen = "Guppie Green"
    case halayBe = "Halayà úBe"
    case hanBlue = "Han Blue"
    case hanPurple = "Han Purple"
    case hansaYellow = "Hansa Yellow"
    case harlequin = "Harlequin"
    case harvardCrimson = "Harvard Crimson"
    case harvestGold = "Harvest Gold"
    case heartGold = "Heart Gold"
    case heliotrope = "Heliotrope"
    case hollywoodCerise = "Hollywood Cerise"
    case honeydew = "Honeydew"
    case honoluluBlue = "Honolulu Blue"
    case hookerSGreen = "Hooker'S Green"
    case hotMagenta = "Hot Magenta"
    case hotPink = "Hot Pink"
    case hunterGreen = "Hunter Green"
    case iceberg = "Iceberg"
    case icterine = "Icterine"
    case imperialBlue = "Imperial Blue"
    case inchworm = "Inchworm"
    case indiaGreen = "India Green"
    case indianRed = "Indian Red"
    case indianYellow = "Indian Yellow"
    case indigo = "Indigo"
    case indigoDye = "Indigo (Dye)"
    case indigoWeb = "Indigo (Web)"
    case internationalKleinBlue = "International Klein Blue"
    case internationalOrangeAerospace = "International Orange (Aerospace)"
    case internationalOrangeEngineering = "International Orange (Engineering)"
    case internationalOrangeGoldenGateBridge = "International Orange (Golden Gate Bridge)"
    case iris = "Iris"
    case isabelline = "Isabelline"
    case islamicGreen = "Islamic Green"
    case ivory = "Ivory"
    case jade = "Jade"
    case jasmine = "Jasmine"
    case jasper = "Jasper"
    case jazzberryJam = "Jazzberry Jam"
    case jet = "Jet"
    case jonquil = "Jonquil"
    case juneBud = "June Bud"
    case jungleGreen = "Jungle Green"
    case kellyGreen = "Kelly Green"
    case kenyanCopper = "Kenyan Copper"
    case khakiHtmlCssKhaki = "Khaki (Html/Css) (Khaki)"
    case khakiX11LightKhaki = "Khaki (X11) (Light Khaki)"
    case kuCrimson = "Ku Crimson"
    case laSalleGreen = "La Salle Green"
    case languidLavender = "Languid Lavender"
    case lapisLazuli = "Lapis Lazuli"
    case laserLemon = "Laser Lemon"
    case laurelGreen = "Laurel Green"
    case lava = "Lava"
    case lavenderBlue = "Lavender Blue"
    case lavenderBlush = "Lavender Blush"
    case lavenderFloral = "Lavender (Floral)"
    case lavenderGray = "Lavender Gray"
    case lavenderIndigo = "Lavender Indigo"
    case lavenderMagenta = "Lavender Magenta"
    case lavenderMist = "Lavender Mist"
    case lavenderPink = "Lavender Pink"
    case lavenderPurple = "Lavender Purple"
    case lavenderRose = "Lavender Rose"
    case lavenderWeb = "Lavender (Web)"
    case lawnGreen = "Lawn Green"
    case lemon = "Lemon"
    case lemonChiffon = "Lemon Chiffon"
    case lemonLime = "Lemon Lime"
    case licorice = "Licorice"
    case lightApricot = "Light Apricot"
    case lightBlue = "Light Blue"
    case lightBrown = "Light Brown"
    case lightCarminePink = "Light Carmine Pink"
    case lightCoral = "Light Coral"
    case lightCornflowerBlue = "Light Cornflower Blue"
    case lightCrimson = "Light Crimson"
    case lightCyan = "Light Cyan"
    case lightFuchsiaPink = "Light Fuchsia Pink"
    case lightGoldenrodYellow = "Light Goldenrod Yellow"
    case lightGray = "Light Gray"
    case lightGreen = "Light Green"
    case lightKhaki = "Light Khaki"
    case lightPastelPurple = "Light Pastel Purple"
    case lightPink = "Light Pink"
    case lightRedOchre = "Light Red Ochre"
    case lightSalmon = "Light Salmon"
    case lightSalmonPink = "Light Salmon Pink"
    case lightSeaGreen = "Light Sea Green"
    case lightSkyBlue = "Light Sky Blue"
    case lightSlateGray = "Light Slate Gray"
    case lightTaupe = "Light Taupe"
    case lightThulianPink = "Light Thulian Pink"
    case lightYellow = "Light Yellow"
    case lilac = "Lilac"
    case limeColorWheel = "Lime (Color Wheel)"
    case limeGreen = "Lime Green"
    case limeWebX11Green = "Lime (Web) (X11 Green)"
    case limerick = "Limerick"
    case lincolnGreen = "Lincoln Green"
    case linen = "Linen"
    case lion = "Lion"
    case littleBoyBlue = "Little Boy Blue"
    case liver = "Liver"
    case lust = "Lust"
    case magenta = "Magenta"
    case magentaDye = "Magenta (Dye)"
    case magentaProcess = "Magenta (Process)"
    case magicMint = "Magic Mint"
    case magnolia = "Magnolia"
    case mahogany = "Mahogany"
    case maize = "Maize"
    case majorelleBlue = "Majorelle Blue"
    case malachite = "Malachite"
    case manatee = "Manatee"
    case mangoTango = "Mango Tango"
    case mantis = "Mantis"
    case mardiGras = "Mardi Gras"
    case maroonCrayola = "Maroon (Crayola)"
    case maroonHtmlCss = "Maroon (Html/Css)"
    case maroonX11 = "Maroon (X11)"
    case mauve = "Mauve"
    case mauveTaupe = "Mauve Taupe"
    case mauvelous = "Mauvelous"
    case mayaBlue = "Maya Blue"
    case meatBrown = "Meat Brown"
    case mediumAquamarine = "Medium Aquamarine"
    case mediumBlue = "Medium Blue"
    case mediumCandyAppleRed = "Medium Candy Apple Red"
    case mediumCarmine = "Medium Carmine"
    case mediumChampagne = "Medium Champagne"
    case mediumElectricBlue = "Medium Electric Blue"
    case mediumJungleGreen = "Medium Jungle Green"
    case mediumLavenderMagenta = "Medium Lavender Magenta"
    case mediumOrchid = "Medium Orchid"
    case mediumPersianBlue = "Medium Persian Blue"
    case mediumPurple = "Medium Purple"
    case mediumRedViolet = "Medium Red-Violet"
    case mediumRuby = "Medium Ruby"
    case mediumSeaGreen = "Medium Sea Green"
    case mediumSlateBlue = "Medium Slate Blue"
    case mediumSpringBud = "Medium Spring Bud"
    case mediumSpringGreen = "Medium Spring Green"
    case mediumTaupe = "Medium Taupe"
    case mediumTurquoise = "Medium Turquoise"
    case mediumTuscanRed = "Medium Tuscan Red"
    case mediumVermilion = "Medium Vermilion"
    case mediumVioletRed = "Medium Violet-Red"
    case mellowApricot = "Mellow Apricot"
    case mellowYellow = "Mellow Yellow"
    case melon = "Melon"
    case midnightBlue = "Midnight Blue"
    case midnightGreenEagleGreen = "Midnight Green (Eagle Green)"
    case mikadoYellow = "Mikado Yellow"
    case mint = "Mint"
    case mintCream = "Mint Cream"
    case mintGreen = "Mint Green"
    case mistyRose = "Misty Rose"
    case moccasin = "Moccasin"
    case modeBeige = "Mode Beige"
    case moonstoneBlue = "Moonstone Blue"
    case mordantRed_19 = "Mordant Red 19"
    case mossGreen = "Moss Green"
    case mountainMeadow = "Mountain Meadow"
    case mountbattenPink = "Mountbatten Pink"
    case msuGreen = "Msu Green"
    case mulberry = "Mulberry"
    case mustard = "Mustard"
    case myrtle = "Myrtle"
    case nadeshikoPink = "Nadeshiko Pink"
    case napierGreen = "Napier Green"
    case naplesYellow = "Naples Yellow"
    case navajoWhite = "Navajo White"
    case navyBlue = "Navy Blue"
    case neonCarrot = "Neon Carrot"
    case neonFuchsia = "Neon Fuchsia"
    case neonGreen = "Neon Green"
    case newYorkPink = "New York Pink"
    case nonPhotoBlue = "Non-Photo Blue"
    case northTexasGreen = "North Texas Green"
    case oceanBoatBlue = "Ocean Boat Blue"
    case ochre = "Ochre"
    case officeGreen = "Office Green"
    case oldGold = "Old Gold"
    case oldLace = "Old Lace"
    case oldLavender = "Old Lavender"
    case oldMauve = "Old Mauve"
    case oldRose = "Old Rose"
//    case olive = "Olive"
    case oliveDrab_7 = "Olive Drab #7"
    case oliveDrabWebOliveDrab_3 = "Olive Drab (Web) (Olive Drab #3)"
    case olivine = "Olivine"
    case onyx = "Onyx"
    case operaMauve = "Opera Mauve"
    case orangeColorWheel = "Orange (Color Wheel)"
    case orangePeel = "Orange Peel"
    case orangeRed = "Orange-Red"
    case orangeRyb = "Orange (Ryb)"
    case orangeWebColor = "Orange (Web Color)"
    case orchid = "Orchid"
    case otterBrown = "Otter Brown"
    case ouCrimsonRed = "Ou Crimson Red"
    case outerSpace = "Outer Space"
    case outrageousOrange = "Outrageous Orange"
    case oxfordBlue = "Oxford Blue"
    case pakistanGreen = "Pakistan Green"
    case palatinateBlue = "Palatinate Blue"
    case palatinatePurple = "Palatinate Purple"
    case paleAqua = "Pale Aqua"
    case paleBlue = "Pale Blue"
    case paleBrown = "Pale Brown"
    case paleCarmine = "Pale Carmine"
    case paleCerulean = "Pale Cerulean"
    case paleChestnut = "Pale Chestnut"
    case paleCopper = "Pale Copper"
    case paleCornflowerBlue = "Pale Cornflower Blue"
    case paleGold = "Pale Gold"
    case paleGoldenrod = "Pale Goldenrod"
    case paleGreen = "Pale Green"
    case paleLavender = "Pale Lavender"
    case paleMagenta = "Pale Magenta"
    case palePink = "Pale Pink"
    case palePlum = "Pale Plum"
    case paleRedViolet = "Pale Red-Violet"
    case paleRobinEggBlue = "Pale Robin Egg Blue"
    case paleSilver = "Pale Silver"
    case paleSpringBud = "Pale Spring Bud"
    case paleTaupe = "Pale Taupe"
    case paleVioletRed = "Pale Violet-Red"
    case pansyPurple = "Pansy Purple"
    case papayaWhip = "Papaya Whip"
    case parisGreen = "Paris Green"
    case pastelBlue = "Pastel Blue"
    case pastelBrown = "Pastel Brown"
    case pastelGray = "Pastel Gray"
    case pastelGreen = "Pastel Green"
    case pastelMagenta = "Pastel Magenta"
    case pastelOrange = "Pastel Orange"
    case pastelPink = "Pastel Pink"
    case pastelPurple = "Pastel Purple"
    case pastelRed = "Pastel Red"
    case pastelViolet = "Pastel Violet"
    case pastelYellow = "Pastel Yellow"
    case patriarch = "Patriarch"
    case payneSGrey = "Payne'S Grey"
    case peach = "Peach"
    case peachCrayola = "Peach (Crayola)"
    case peachOrange = "Peach-Orange"
    case peachPuff = "Peach Puff"
    case peachYellow = "Peach-Yellow"
    case pear = "Pear"
    case pearl = "Pearl"
    case pearlAqua = "Pearl Aqua"
    case pearlyPurple = "Pearly Purple"
    case peridot = "Peridot"
    case periwinkle = "Periwinkle"
    case persianBlue = "Persian Blue"
    case persianGreen = "Persian Green"
    case persianIndigo = "Persian Indigo"
    case persianOrange = "Persian Orange"
    case persianPink = "Persian Pink"
    case persianPlum = "Persian Plum"
    case persianRed = "Persian Red"
    case persianRose = "Persian Rose"
    case persimmon = "Persimmon"
    case peru = "Peru"
    case phlox = "Phlox"
    case phthaloBlue = "Phthalo Blue"
    case phthaloGreen = "Phthalo Green"
    case piggyPink = "Piggy Pink"
    case pineGreen = "Pine Green"
    case pink = "Pink"
    case pinkLace = "Pink Lace"
    case pinkOrange = "Pink-Orange"
    case pinkPearl = "Pink Pearl"
    case pinkSherbet = "Pink Sherbet"
    case pistachio = "Pistachio"
    case platinum = "Platinum"
    case plumTraditional = "Plum (Traditional)"
    case plumWeb = "Plum (Web)"
    case portlandOrange = "Portland Orange"
    case powderBlueWeb = "Powder Blue (Web)"
    case princetonOrange = "Princeton Orange"
    case prune = "Prune"
    case prussianBlue = "Prussian Blue"
    case psychedelicPurple = "Psychedelic Purple"
    case puce = "Puce"
    case pumpkin = "Pumpkin"
    case purpleHeart = "Purple Heart"
    case purpleHtmlCss = "Purple (Html/Css)"
    case purpleMountainMajesty = "Purple Mountain Majesty"
    case purpleMunsell = "Purple (Munsell)"
    case purplePizzazz = "Purple Pizzazz"
    case purpleTaupe = "Purple Taupe"
    case purpleX11 = "Purple (X11)"
    case quartz = "Quartz"
    case rackley = "Rackley"
    case radicalRed = "Radical Red"
    case rajah = "Rajah"
    case raspberry = "Raspberry"
    case raspberryGlace = "Raspberry Glace"
    case raspberryPink = "Raspberry Pink"
    case raspberryRose = "Raspberry Rose"
    case rawUmber = "Raw Umber"
    case razzleDazzleRose = "Razzle Dazzle Rose"
    case razzmatazz = "Razzmatazz"
//    case red = "Red"
    case redBrown = "Red-Brown"
    case redDevil = "Red Devil"
    case redMunsell = "Red (Munsell)"
    case redNcs = "Red (Ncs)"
    case redOrange = "Red-Orange"
    case redPigment = "Red (Pigment)"
    case redRyb = "Red (Ryb)"
    case redViolet = "Red-Violet"
    case redwood = "Redwood"
    case regalia = "Regalia"
    case resolutionBlue = "Resolution Blue"
    case richBlack = "Rich Black"
    case richBrilliantLavender = "Rich Brilliant Lavender"
    case richCarmine = "Rich Carmine"
    case richElectricBlue = "Rich Electric Blue"
    case richLavender = "Rich Lavender"
    case richLilac = "Rich Lilac"
    case richMaroon = "Rich Maroon"
    case rifleGreen = "Rifle Green"
    case robinEggBlue = "Robin Egg Blue"
    case rose = "Rose"
    case roseBonbon = "Rose Bonbon"
    case roseEbony = "Rose Ebony"
    case roseGold = "Rose Gold"
    case roseMadder = "Rose Madder"
    case rosePink = "Rose Pink"
    case roseQuartz = "Rose Quartz"
    case roseTaupe = "Rose Taupe"
    case roseVale = "Rose Vale"
    case rosewood = "Rosewood"
    case rossoCorsa = "Rosso Corsa"
    case rosyBrown = "Rosy Brown"
    case royalAzure = "Royal Azure"
    case royalBlueTraditional = "Royal Blue (Traditional)"
    case royalBlueWeb = "Royal Blue (Web)"
    case royalFuchsia = "Royal Fuchsia"
    case royalPurple = "Royal Purple"
    case royalYellow = "Royal Yellow"
    case rubineRed = "Rubine Red"
    case ruby = "Ruby"
    case rubyRed = "Ruby Red"
    case ruddy = "Ruddy"
    case ruddyBrown = "Ruddy Brown"
    case ruddyPink = "Ruddy Pink"
    case rufous = "Rufous"
    case russet = "Russet"
    case rust = "Rust"
    case rustyRed = "Rusty Red"
    case sacramentoStateGreen = "Sacramento State Green"
    case saddleBrown = "Saddle Brown"
    case safetyOrangeBlazeOrange = "Safety Orange (Blaze Orange)"
    case saffron = "Saffron"
    case salmon = "Salmon"
    case salmonPink = "Salmon Pink"
    case sand = "Sand"
    case sandDune = "Sand Dune"
    case sandstorm = "Sandstorm"
    case sandyBrown = "Sandy Brown"
    case sandyTaupe = "Sandy Taupe"
    case sangria = "Sangria"
    case sapGreen = "Sap Green"
    case sapphire = "Sapphire"
    case sapphireBlue = "Sapphire Blue"
    case satinSheenGold = "Satin Sheen Gold"
    case scarlet = "Scarlet"
    case scarletCrayola = "Scarlet (Crayola)"
    case schoolBusYellow = "School Bus Yellow"
    case screaminGreen = "Screamin' Green"
    case seaBlue = "Sea Blue"
    case seaGreen = "Sea Green"
    case sealBrown = "Seal Brown"
    case seashell = "Seashell"
    case selectiveYellow = "Selective Yellow"
    case sepia = "Sepia"
    case shadow = "Shadow"
    case shamrockGreen = "Shamrock Green"
    case shockingPink = "Shocking Pink"
    case shockingPinkCrayola = "Shocking Pink (Crayola)"
    case sienna = "Sienna"
//    case silver = "Silver"
    case sinopia = "Sinopia"
    case skobeloff = "Skobeloff"
    case skyBlue = "Sky Blue"
    case skyMagenta = "Sky Magenta"
    case slateBlue = "Slate Blue"
    case slateGray = "Slate Gray"
    case smaltDarkPowderBlue = "Smalt (Dark Powder Blue)"
    case smokeyTopaz = "Smokey Topaz"
    case smokyBlack = "Smoky Black"
    case snow = "Snow"
    case spiroDiscoBall = "Spiro Disco Ball"
    case springBud = "Spring Bud"
    case springGreen = "Spring Green"
    case stPatrickSBlue = "St. Patrick'S Blue"
    case steelBlue = "Steel Blue"
    case stilDeGrainYellow = "Stil De Grain Yellow"
    case stizza = "Stizza"
    case stormcloud = "Stormcloud"
    case straw = "Straw"
    case sunglow = "Sunglow"
    case sunset = "Sunset"
    case tan = "Tan"
    case tangelo = "Tangelo"
    case tangerine = "Tangerine"
    case tangerineYellow = "Tangerine Yellow"
    case tangoPink = "Tango Pink"
    case taupe = "Taupe"
    case taupeGray = "Taupe Gray"
    case teaGreen = "Tea Green"
    case teaRoseOrange = "Tea Rose (Orange)"
    case teaRoseRose = "Tea Rose (Rose)"
//    case teal = "Teal"
    case tealBlue = "Teal Blue"
    case tealGreen = "Teal Green"
    case telemagenta = "Telemagenta"
    case tennTawny = "Tenné (Tawny)"
    case terraCotta = "Terra Cotta"
    case thistle = "Thistle"
    case thulianPink = "Thulian Pink"
    case tickleMePink = "Tickle Me Pink"
    case tiffanyBlue = "Tiffany Blue"
    case tigerSEye = "Tiger'S Eye"
    case timberwolf = "Timberwolf"
    case titaniumYellow = "Titanium Yellow"
    case tomato = "Tomato"
    case toolbox = "Toolbox"
    case topaz = "Topaz"
    case tractorRed = "Tractor Red"
    case trolleyGrey = "Trolley Grey"
    case tropicalRainForest = "Tropical Rain Forest"
    case trueBlue = "True Blue"
    case tuftsBlue = "Tufts Blue"
    case tumbleweed = "Tumbleweed"
    case turkishRose = "Turkish Rose"
    case turquoise = "Turquoise"
    case turquoiseBlue = "Turquoise Blue"
    case turquoiseGreen = "Turquoise Green"
    case tuscanRed = "Tuscan Red"
    case twilightLavender = "Twilight Lavender"
    case tyrianPurple = "Tyrian Purple"
    case uaBlue = "Ua Blue"
    case uaRed = "Ua Red"
    case ube = "Ube"
    case uclaBlue = "Ucla Blue"
    case uclaGold = "Ucla Gold"
    case ufoGreen = "Ufo Green"
    case ultraPink = "Ultra Pink"
    case ultramarine = "Ultramarine"
    case ultramarineBlue = "Ultramarine Blue"
    case umber = "Umber"
    case unbleachedSilk = "Unbleached Silk"
    case unitedNationsBlue = "United Nations Blue"
    case universityOfCaliforniaGold = "University Of California Gold"
    case unmellowYellow = "Unmellow Yellow"
    case upForestGreen = "Up Forest Green"
    case upMaroon = "Up Maroon"
    case upsdellRed = "Upsdell Red"
    case urobilin = "Urobilin"
    case usafaBlue = "Usafa Blue"
    case uscCardinal = "Usc Cardinal"
    case uscGold = "Usc Gold"
    case utahCrimson = "Utah Crimson"
    case vanilla = "Vanilla"
    case vegasGold = "Vegas Gold"
    case venetianRed = "Venetian Red"
    case verdigris = "Verdigris"
    case vermilionCinnabar = "Vermilion (Cinnabar)"
    case vermilionPlochere = "Vermilion (Plochere)"
    case veronica = "Veronica"
    case violet = "Violet"
    case violetBlue = "Violet-Blue"
    case violetColorWheel = "Violet (Color Wheel)"
    case violetRyb = "Violet (Ryb)"
    case violetWeb = "Violet (Web)"
    case viridian = "Viridian"
    case vividAuburn = "Vivid Auburn"
    case vividBurgundy = "Vivid Burgundy"
    case vividCerise = "Vivid Cerise"
    case vividTangerine = "Vivid Tangerine"
    case vividViolet = "Vivid Violet"
    case warmBlack = "Warm Black"
    case waterspout = "Waterspout"
    case wenge = "Wenge"
    case wheat = "Wheat"
//    case white = "White"
    case whiteSmoke = "White Smoke"
    case wildBlueYonder = "Wild Blue Yonder"
    case wildStrawberry = "Wild Strawberry"
    case wildWatermelon = "Wild Watermelon"
    case wine = "Wine"
    case wineDregs = "Wine Dregs"
    case wisteria = "Wisteria"
    case woodBrown = "Wood Brown"
    case xanadu = "Xanadu"
    case yaleBlue = "Yale Blue"
//    case yellow = "Yellow"
    case yellowGreen = "Yellow-Green"
    case yellowMunsell = "Yellow (Munsell)"
    case yellowNcs = "Yellow (Ncs)"
    case yellowOrange = "Yellow Orange"
    case yellowProcess = "Yellow (Process)"
    case yellowRyb = "Yellow (Ryb)"
    case zaffre = "Zaffre"
    case zinnwalditeBrown = "Zinnwaldite Brown"
    
    public var hexString: String {
        switch self {
            
        case .basicWhite: "#FFFFFF"
        case .basicSilver: "#C0C0C0"
        case .basicGray: "#808080"
        case .basicBlack: "#000000"
        case .basicRed: "#FF0000"
        case .basicMaroon: "#800000"
        case .basicYellow: "#FFFF00"
        case .basicOlive: "#808000"
        case .basicLime: "#00FF00"
        case .basicGreen: "#008000"
        case .basicAqua: "#00FFFF"
        case .basicTeal: "#008080"
        case .basicBlue: "#0000FF"
        case .basicNavy: "#000080"
        case .basicFuchsia: "#FF00FF"
        case .basicPurple: "#800080"
            
        case .airForceBlueRaf: "#5D8AA8"
        case .airForceBlueUsaf: "#00308F"
        case .airSuperiorityBlue: "#72A0C1"
        case .alabamaCrimson: "#A32638"
        case .aliceBlue: "#F0F8FF"
        case .alizarinCrimson: "#E32636"
        case .alloyOrange: "#C46210"
        case .almond: "#EFDECD"
        case .amaranth: "#E52B50"
        case .amber: "#FFBF00"
        case .amberSaeEce: "#FF7E00"
        case .americanRose: "#FF033E"
        case .amethyst: "#9966CC"
        case .androidGreen: "#A4C639"
        case .antiFlashWhite: "#F2F3F4"
        case .antiqueBrass: "#CD9575"
        case .antiqueFuchsia: "#915C83"
        case .antiqueRuby: "#841B2D"
        case .antiqueWhite: "#FAEBD7"
        case .aoEnglish: "#008000"
        case .appleGreen: "#8DB600"
        case .apricot: "#FBCEB1"
//        case .aqua: "#00FFFF"
        case .aquamarine: "#7FFFD4"
        case .armyGreen: "#4B5320"
        case .arsenic: "#3B444B"
        case .arylideYellow: "#E9D66B"
        case .ashGrey: "#B2BEB5"
        case .asparagus: "#87A96B"
        case .atomicTangerine: "#FF9966"
        case .auburn: "#A52A2A"
        case .aureolin: "#FDEE00"
        case .aurometalsaurus: "#6E7F80"
        case .avocado: "#568203"
        case .azure: "#007FFF"
        case .azureMistWeb: "#F0FFFF"
        case .babyBlue: "#89CFF0"
        case .babyBlueEyes: "#A1CAF1"
        case .babyPink: "#F4C2C2"
        case .ballBlue: "#21ABCD"
        case .bananaMania: "#FAE7B5"
        case .bananaYellow: "#FFE135"
        case .barnRed: "#7C0A02"
        case .battleshipGrey: "#848482"
        case .bazaar: "#98777B"
        case .beauBlue: "#BCD4E6"
        case .beaver: "#9F8170"
        case .beige: "#F5F5DC"
        case .bigDipORuby: "#9C2542"
        case .bisque: "#FFE4C4"
        case .bistre: "#3D2B1F"
        case .bittersweet: "#FE6F5E"
        case .bittersweetShimmer: "#BF4F51"
//        case .black: "#000000"
        case .blackBean: "#3D0C02"
        case .blackLeatherJacket: "#253529"
        case .blackOlive: "#3B3C36"
        case .blanchedAlmond: "#FFEBCD"
        case .blastOffBronze: "#A57164"
        case .bleuDeFrance: "#318CE7"
        case .blizzardBlue: "#ACE5EE"
        case .blond: "#FAF0BE"
//        case .blue: "#0000FF"
        case .blueBell: "#A2A2D0"
        case .blueCrayola: "#1F75FE"
        case .blueGray: "#6699CC"
        case .blueGreen: "#0D98BA"
        case .blueMunsell: "#0093AF"
        case .blueNcs: "#0087BD"
        case .bluePigment: "#333399"
        case .blueRyb: "#0247FE"
        case .blueSapphire: "#126180"
        case .blueViolet: "#8A2BE2"
        case .blush: "#DE5D83"
        case .bole: "#79443B"
        case .bondiBlue: "#0095B6"
        case .bone: "#E3DAC9"
        case .bostonUniversityRed: "#CC0000"
        case .bottleGreen: "#006A4E"
        case .boysenberry: "#873260"
        case .brandeisBlue: "#0070FF"
        case .brass: "#B5A642"
        case .brickRed: "#CB4154"
        case .brightCerulean: "#1DACD6"
        case .brightGreen: "#66FF00"
        case .brightLavender: "#BF94E4"
        case .brightMaroon: "#C32148"
        case .brightPink: "#FF007F"
        case .brightTurquoise: "#08E8DE"
        case .brightUbe: "#D19FE8"
        case .brilliantLavender: "#F4BBFF"
        case .brilliantRose: "#FF55A3"
        case .brinkPink: "#FB607F"
        case .britishRacingGreen: "#004225"
        case .bronze: "#CD7F32"
        case .brownTraditional: "#964B00"
        case .brownWeb: "#A52A2A"
        case .bubbleGum: "#FFC1CC"
        case .bubbles: "#E7FEFF"
        case .buff: "#F0DC82"
        case .bulgarianRose: "#480607"
        case .burgundy: "#800020"
        case .burlywood: "#DEB887"
        case .burntOrange: "#CC5500"
        case .burntSienna: "#E97451"
        case .burntUmber: "#8A3324"
        case .byzantine: "#BD33A4"
        case .byzantium: "#702963"
        case .cadet: "#536872"
        case .cadetBlue: "#5F9EA0"
        case .cadetGrey: "#91A3B0"
        case .cadmiumGreen: "#006B3C"
        case .cadmiumOrange: "#ED872D"
        case .cadmiumRed: "#E30022"
        case .cadmiumYellow: "#FFF600"
        case .cafAuLait: "#A67B5B"
        case .cafNoir: "#4B3621"
        case .calPolyGreen: "#1E4D2B"
        case .cambridgeBlue: "#A3C1AD"
        case .camel: "#C19A6B"
        case .cameoPink: "#EFBBCC"
        case .camouflageGreen: "#78866B"
        case .canaryYellow: "#FFEF00"
        case .candyAppleRed: "#FF0800"
        case .candyPink: "#E4717A"
        case .capri: "#00BFFF"
        case .caputMortuum: "#592720"
        case .cardinal: "#C41E3A"
        case .caribbeanGreen: "#00CC99"
        case .carmine: "#960018"
        case .carmineMP: "#D70040"
        case .carminePink: "#EB4C42"
        case .carmineRed: "#FF0038"
        case .carnationPink: "#FFA6C9"
        case .carnelian: "#B31B1B"
        case .carolinaBlue: "#99BADD"
        case .carrotOrange: "#ED9121"
        case .catalinaBlue: "#062A78"
        case .ceil: "#92A1CF"
        case .celadon: "#ACE1AF"
        case .celadonBlue: "#007BA7"
        case .celadonGreen: "#2F847C"
        case .celesteColour: "#B2FFFF"
        case .celestialBlue: "#4997D0"
        case .cerise: "#DE3163"
        case .cerisePink: "#EC3B83"
        case .cerulean: "#007BA7"
        case .ceruleanBlue: "#2A52BE"
        case .ceruleanFrost: "#6D9BC3"
        case .cgBlue: "#007AA5"
        case .cgRed: "#E03C31"
        case .chamoisee: "#A0785A"
        case .champagne: "#FAD6A5"
        case .charcoal: "#36454F"
        case .charmPink: "#E68FAC"
        case .chartreuseTraditional: "#DFFF00"
        case .chartreuseWeb: "#7FFF00"
        case .cherry: "#DE3163"
        case .cherryBlossomPink: "#FFB7C5"
        case .chestnut: "#CD5C5C"
        case .chinaPink: "#DE6FA1"
        case .chinaRose: "#A8516E"
        case .chineseRed: "#AA381E"
        case .chocolateTraditional: "#7B3F00"
        case .chocolateWeb: "#D2691E"
        case .chromeYellow: "#FFA700"
        case .cinereous: "#98817B"
        case .cinnabar: "#E34234"
        case .cinnamon: "#D2691E"
        case .citrine: "#E4D00A"
        case .classicRose: "#FBCCE7"
        case .cobalt: "#0047AB"
        case .cocoaBrown: "#D2691E"
        case .coffee: "#6F4E37"
        case .columbiaBlue: "#9BDDFF"
        case .congoPink: "#F88379"
        case .coolBlack: "#002E63"
        case .coolGrey: "#8C92AC"
        case .copper: "#B87333"
        case .copperCrayola: "#DA8A67"
        case .copperPenny: "#AD6F69"
        case .copperRed: "#CB6D51"
        case .copperRose: "#996666"
        case .coquelicot: "#FF3800"
        case .coral: "#FF7F50"
        case .coralPink: "#F88379"
        case .coralRed: "#FF4040"
        case .cordovan: "#893F45"
        case .corn: "#FBEC5D"
        case .cornellRed: "#B31B1B"
        case .cornflowerBlue: "#6495ED"
        case .cornsilk: "#FFF8DC"
        case .cosmicLatte: "#FFF8E7"
        case .cottonCandy: "#FFBCD9"
        case .cream: "#FFFDD0"
        case .crimson: "#DC143C"
        case .crimsonGlory: "#BE0032"
        case .cyan: "#00FFFF"
        case .cyanProcess: "#00B7EB"
        case .daffodil: "#FFFF31"
        case .dandelion: "#F0E130"
        case .darkBlue: "#00008B"
        case .darkBrown: "#654321"
        case .darkByzantium: "#5D3954"
        case .darkCandyAppleRed: "#A40000"
        case .darkCerulean: "#08457E"
        case .darkChestnut: "#986960"
        case .darkCoral: "#CD5B45"
        case .darkCyan: "#008B8B"
        case .darkElectricBlue: "#536878"
        case .darkGoldenrod: "#B8860B"
        case .darkGray: "#A9A9A9"
        case .darkGreen: "#013220"
        case .darkImperialBlue: "#00416A"
        case .darkJungleGreen: "#1A2421"
        case .darkKhaki: "#BDB76B"
        case .darkLava: "#483C32"
        case .darkLavender: "#734F96"
        case .darkMagenta: "#8B008B"
        case .darkMidnightBlue: "#003366"
        case .darkOliveGreen: "#556B2F"
        case .darkOrange: "#FF8C00"
        case .darkOrchid: "#9932CC"
        case .darkPastelBlue: "#779ECB"
        case .darkPastelGreen: "#03C03C"
        case .darkPastelPurple: "#966FD6"
        case .darkPastelRed: "#C23B22"
        case .darkPink: "#E75480"
        case .darkPowderBlue: "#003399"
        case .darkRaspberry: "#872657"
        case .darkRed: "#8B0000"
        case .darkSalmon: "#E9967A"
        case .darkScarlet: "#560319"
        case .darkSeaGreen: "#8FBC8F"
        case .darkSienna: "#3C1414"
        case .darkSlateBlue: "#483D8B"
        case .darkSlateGray: "#2F4F4F"
        case .darkSpringGreen: "#177245"
        case .darkTan: "#918151"
        case .darkTangerine: "#FFA812"
        case .darkTaupe: "#483C32"
        case .darkTerraCotta: "#CC4E5C"
        case .darkTurquoise: "#00CED1"
        case .darkViolet: "#9400D3"
        case .darkYellow: "#9B870C"
        case .dartmouthGreen: "#00703C"
        case .davySGrey: "#555555"
        case .debianRed: "#D70A53"
        case .deepCarmine: "#A9203E"
        case .deepCarminePink: "#EF3038"
        case .deepCarrotOrange: "#E9692C"
        case .deepCerise: "#DA3287"
        case .deepChampagne: "#FAD6A5"
        case .deepChestnut: "#B94E48"
        case .deepCoffee: "#704241"
        case .deepFuchsia: "#C154C1"
        case .deepJungleGreen: "#004B49"
        case .deepLilac: "#9955BB"
        case .deepMagenta: "#CC00CC"
        case .deepPeach: "#FFCBA4"
        case .deepPink: "#FF1493"
        case .deepRuby: "#843F5B"
        case .deepSaffron: "#FF9933"
        case .deepSkyBlue: "#00BFFF"
        case .deepTuscanRed: "#66424D"
        case .denim: "#1560BD"
        case .desert: "#C19A6B"
        case .desertSand: "#EDC9AF"
        case .dimGray: "#696969"
        case .dodgerBlue: "#1E90FF"
        case .dogwoodRose: "#D71868"
        case .dollarBill: "#85BB65"
        case .drab: "#967117"
        case .dukeBlue: "#00009C"
        case .earthYellow: "#E1A95F"
        case .ebony: "#555D50"
        case .ecru: "#C2B280"
        case .eggplant: "#614051"
        case .eggshell: "#F0EAD6"
        case .egyptianBlue: "#1034A6"
        case .electricBlue: "#7DF9FF"
        case .electricCrimson: "#FF003F"
        case .electricCyan: "#00FFFF"
        case .electricGreen: "#00FF00"
        case .electricIndigo: "#6F00FF"
        case .electricLavender: "#F4BBFF"
        case .electricLime: "#CCFF00"
        case .electricPurple: "#BF00FF"
        case .electricUltramarine: "#3F00FF"
        case .electricViolet: "#8F00FF"
        case .electricYellow: "#FFFF00"
        case .emerald: "#50C878"
        case .englishLavender: "#B48395"
        case .etonBlue: "#96C8A2"
        case .fallow: "#C19A6B"
        case .faluRed: "#801818"
        case .fandango: "#B53389"
        case .fashionFuchsia: "#F400A1"
        case .fawn: "#E5AA70"
        case .feldgrau: "#4D5D53"
        case .fernGreen: "#4F7942"
        case .ferrariRed: "#FF2800"
        case .fieldDrab: "#6C541E"
        case .fireEngineRed: "#CE2029"
        case .firebrick: "#B22222"
        case .flame: "#E25822"
        case .flamingoPink: "#FC8EAC"
        case .flavescent: "#F7E98E"
        case .flax: "#EEDC82"
        case .floralWhite: "#FFFAF0"
        case .fluorescentOrange: "#FFBF00"
        case .fluorescentPink: "#FF1493"
        case .fluorescentYellow: "#CCFF00"
        case .folly: "#FF004F"
        case .forestGreenTraditional: "#014421"
        case .forestGreenWeb: "#228B22"
        case .frenchBeige: "#A67B5B"
        case .frenchBlue: "#0072BB"
        case .frenchLilac: "#86608E"
        case .frenchLime: "#CCFF00"
        case .frenchRaspberry: "#C72C48"
        case .frenchRose: "#F64A8A"
//        case .fuchsia: "#FF00FF"
        case .fuchsiaCrayola: "#C154C1"
        case .fuchsiaPink: "#FF77FF"
        case .fuchsiaRose: "#C74375"
        case .fulvous: "#E48400"
        case .fuzzyWuzzy: "#CC6666"
        case .gainsboro: "#DCDCDC"
        case .gamboge: "#E49B0F"
        case .ghostWhite: "#F8F8FF"
        case .ginger: "#B06500"
        case .glaucous: "#6082B6"
        case .glitter: "#E6E8FA"
        case .goldMetallic: "#D4AF37"
        case .goldWebGolden: "#FFD700"
        case .goldenBrown: "#996515"
        case .goldenPoppy: "#FCC200"
        case .goldenYellow: "#FFDF00"
        case .goldenrod: "#DAA520"
        case .grannySmithApple: "#A8E4A0"
//        case .gray: "#808080"
        case .grayAsparagus: "#465945"
        case .grayHtmlCssGray: "#808080"
        case .grayX11Gray: "#BEBEBE"
        case .greenColorWheelX11Green: "#00FF00"
        case .greenCrayola: "#1CAC78"
        case .greenHtmlCssGreen: "#008000"
        case .greenMunsell: "#00A877"
        case .greenNcs: "#009F6B"
        case .greenPigment: "#00A550"
        case .greenRyb: "#66B032"
        case .greenYellow: "#ADFF2F"
        case .grullo: "#A99A86"
        case .guppieGreen: "#00FF7F"
        case .halayBe: "#663854"
        case .hanBlue: "#446CCF"
        case .hanPurple: "#5218FA"
        case .hansaYellow: "#E9D66B"
        case .harlequin: "#3FFF00"
        case .harvardCrimson: "#C90016"
        case .harvestGold: "#DA9100"
        case .heartGold: "#808000"
        case .heliotrope: "#DF73FF"
        case .hollywoodCerise: "#F400A1"
        case .honeydew: "#F0FFF0"
        case .honoluluBlue: "#007FBF"
        case .hookerSGreen: "#49796B"
        case .hotMagenta: "#FF1DCE"
        case .hotPink: "#FF69B4"
        case .hunterGreen: "#355E3B"
        case .iceberg: "#71A6D2"
        case .icterine: "#FCF75E"
        case .imperialBlue: "#002395"
        case .inchworm: "#B2EC5D"
        case .indiaGreen: "#138808"
        case .indianRed: "#CD5C5C"
        case .indianYellow: "#E3A857"
        case .indigo: "#6F00FF"
        case .indigoDye: "#00416A"
        case .indigoWeb: "#4B0082"
        case .internationalKleinBlue: "#002FA7"
        case .internationalOrangeAerospace: "#FF4F00"
        case .internationalOrangeEngineering: "#BA160C"
        case .internationalOrangeGoldenGateBridge: "#C0362C"
        case .iris: "#5A4FCF"
        case .isabelline: "#F4F0EC"
        case .islamicGreen: "#009000"
        case .ivory: "#FFFFF0"
        case .jade: "#00A86B"
        case .jasmine: "#F8DE7E"
        case .jasper: "#D73B3E"
        case .jazzberryJam: "#A50B5E"
        case .jet: "#343434"
        case .jonquil: "#FADA5E"
        case .juneBud: "#BDDA57"
        case .jungleGreen: "#29AB87"
        case .kellyGreen: "#4CBB17"
        case .kenyanCopper: "#7C1C05"
        case .khakiHtmlCssKhaki: "#C3B091"
        case .khakiX11LightKhaki: "#F0E68C"
        case .kuCrimson: "#E8000D"
        case .laSalleGreen: "#087830"
        case .languidLavender: "#D6CADD"
        case .lapisLazuli: "#26619C"
        case .laserLemon: "#FEFE22"
        case .laurelGreen: "#A9BA9D"
        case .lava: "#CF1020"
        case .lavenderBlue: "#CCCCFF"
        case .lavenderBlush: "#FFF0F5"
        case .lavenderFloral: "#B57EDC"
        case .lavenderGray: "#C4C3D0"
        case .lavenderIndigo: "#9457EB"
        case .lavenderMagenta: "#EE82EE"
        case .lavenderMist: "#E6E6FA"
        case .lavenderPink: "#FBAED2"
        case .lavenderPurple: "#967BB6"
        case .lavenderRose: "#FBA0E3"
        case .lavenderWeb: "#E6E6FA"
        case .lawnGreen: "#7CFC00"
        case .lemon: "#FFF700"
        case .lemonChiffon: "#FFFACD"
        case .lemonLime: "#E3FF00"
        case .licorice: "#1A1110"
        case .lightApricot: "#FDD5B1"
        case .lightBlue: "#ADD8E6"
        case .lightBrown: "#B5651D"
        case .lightCarminePink: "#E66771"
        case .lightCoral: "#F08080"
        case .lightCornflowerBlue: "#93CCEA"
        case .lightCrimson: "#F56991"
        case .lightCyan: "#E0FFFF"
        case .lightFuchsiaPink: "#F984EF"
        case .lightGoldenrodYellow: "#FAFAD2"
        case .lightGray: "#D3D3D3"
        case .lightGreen: "#90EE90"
        case .lightKhaki: "#F0E68C"
        case .lightPastelPurple: "#B19CD9"
        case .lightPink: "#FFB6C1"
        case .lightRedOchre: "#E97451"
        case .lightSalmon: "#FFA07A"
        case .lightSalmonPink: "#FF9999"
        case .lightSeaGreen: "#20B2AA"
        case .lightSkyBlue: "#87CEFA"
        case .lightSlateGray: "#778899"
        case .lightTaupe: "#B38B6D"
        case .lightThulianPink: "#E68FAC"
        case .lightYellow: "#FFFFE0"
        case .lilac: "#C8A2C8"
        case .limeColorWheel: "#BFFF00"
        case .limeGreen: "#32CD32"
        case .limeWebX11Green: "#00FF00"
        case .limerick: "#9DC209"
        case .lincolnGreen: "#195905"
        case .linen: "#FAF0E6"
        case .lion: "#C19A6B"
        case .littleBoyBlue: "#6CA0DC"
        case .liver: "#534B4F"
        case .lust: "#E62020"
        case .magenta: "#FF00FF"
        case .magentaDye: "#CA1F7B"
        case .magentaProcess: "#FF0090"
        case .magicMint: "#AAF0D1"
        case .magnolia: "#F8F4FF"
        case .mahogany: "#C04000"
        case .maize: "#FBEC5D"
        case .majorelleBlue: "#6050DC"
        case .malachite: "#0BDA51"
        case .manatee: "#979AAA"
        case .mangoTango: "#FF8243"
        case .mantis: "#74C365"
        case .mardiGras: "#880085"
        case .maroonCrayola: "#C32148"
        case .maroonHtmlCss: "#800000"
        case .maroonX11: "#B03060"
        case .mauve: "#E0B0FF"
        case .mauveTaupe: "#915F6D"
        case .mauvelous: "#EF98AA"
        case .mayaBlue: "#73C2FB"
        case .meatBrown: "#E5B73B"
        case .mediumAquamarine: "#66DDAA"
        case .mediumBlue: "#0000CD"
        case .mediumCandyAppleRed: "#E2062C"
        case .mediumCarmine: "#AF4035"
        case .mediumChampagne: "#F3E5AB"
        case .mediumElectricBlue: "#035096"
        case .mediumJungleGreen: "#1C352D"
        case .mediumLavenderMagenta: "#DDA0DD"
        case .mediumOrchid: "#BA55D3"
        case .mediumPersianBlue: "#0067A5"
        case .mediumPurple: "#9370DB"
        case .mediumRedViolet: "#BB3385"
        case .mediumRuby: "#AA4069"
        case .mediumSeaGreen: "#3CB371"
        case .mediumSlateBlue: "#7B68EE"
        case .mediumSpringBud: "#C9DC87"
        case .mediumSpringGreen: "#00FA9A"
        case .mediumTaupe: "#674C47"
        case .mediumTurquoise: "#48D1CC"
        case .mediumTuscanRed: "#79443B"
        case .mediumVermilion: "#D9603B"
        case .mediumVioletRed: "#C71585"
        case .mellowApricot: "#F8B878"
        case .mellowYellow: "#F8DE7E"
        case .melon: "#FDBCB4"
        case .midnightBlue: "#191970"
        case .midnightGreenEagleGreen: "#004953"
        case .mikadoYellow: "#FFC40C"
        case .mint: "#3EB489"
        case .mintCream: "#F5FFFA"
        case .mintGreen: "#98FF98"
        case .mistyRose: "#FFE4E1"
        case .moccasin: "#FAEBD7"
        case .modeBeige: "#967117"
        case .moonstoneBlue: "#73A9C2"
        case .mordantRed_19: "#AE0C00"
        case .mossGreen: "#ADDFAD"
        case .mountainMeadow: "#30BA8F"
        case .mountbattenPink: "#997A8D"
        case .msuGreen: "#18453B"
        case .mulberry: "#C54B8C"
        case .mustard: "#FFDB58"
        case .myrtle: "#21421E"
        case .nadeshikoPink: "#F6ADC6"
        case .napierGreen: "#2A8000"
        case .naplesYellow: "#FADA5E"
        case .navajoWhite: "#FFDEAD"
        case .navyBlue: "#000080"
        case .neonCarrot: "#FFA343"
        case .neonFuchsia: "#FE4164"
        case .neonGreen: "#39FF14"
        case .newYorkPink: "#D7837F"
        case .nonPhotoBlue: "#A4DDED"
        case .northTexasGreen: "#059033"
        case .oceanBoatBlue: "#0077BE"
        case .ochre: "#CC7722"
        case .officeGreen: "#008000"
        case .oldGold: "#CFB53B"
        case .oldLace: "#FDF5E6"
        case .oldLavender: "#796878"
        case .oldMauve: "#673147"
        case .oldRose: "#C08081"
//        case .olive: "#808000"
        case .oliveDrab_7: "#3C341F"
        case .oliveDrabWebOliveDrab_3: "#6B8E23"
        case .olivine: "#9AB973"
        case .onyx: "#353839"
        case .operaMauve: "#B784A7"
        case .orangeColorWheel: "#FF7F00"
        case .orangePeel: "#FF9F00"
        case .orangeRed: "#FF4500"
        case .orangeRyb: "#FB9902"
        case .orangeWebColor: "#FFA500"
        case .orchid: "#DA70D6"
        case .otterBrown: "#654321"
        case .ouCrimsonRed: "#990000"
        case .outerSpace: "#414A4C"
        case .outrageousOrange: "#FF6E4A"
        case .oxfordBlue: "#002147"
        case .pakistanGreen: "#006600"
        case .palatinateBlue: "#273BE2"
        case .palatinatePurple: "#682860"
        case .paleAqua: "#BCD4E6"
        case .paleBlue: "#AFEEEE"
        case .paleBrown: "#987654"
        case .paleCarmine: "#AF4035"
        case .paleCerulean: "#9BC4E2"
        case .paleChestnut: "#DDADAF"
        case .paleCopper: "#DA8A67"
        case .paleCornflowerBlue: "#ABCDEF"
        case .paleGold: "#E6BE8A"
        case .paleGoldenrod: "#EEE8AA"
        case .paleGreen: "#98FB98"
        case .paleLavender: "#DCD0FF"
        case .paleMagenta: "#F984E5"
        case .palePink: "#FADADD"
        case .palePlum: "#DDA0DD"
        case .paleRedViolet: "#DB7093"
        case .paleRobinEggBlue: "#96DED1"
        case .paleSilver: "#C9C0BB"
        case .paleSpringBud: "#ECEBBD"
        case .paleTaupe: "#BC987E"
        case .paleVioletRed: "#DB7093"
        case .pansyPurple: "#78184A"
        case .papayaWhip: "#FFEFD5"
        case .parisGreen: "#50C878"
        case .pastelBlue: "#AEC6CF"
        case .pastelBrown: "#836953"
        case .pastelGray: "#CFCFC4"
        case .pastelGreen: "#77DD77"
        case .pastelMagenta: "#F49AC2"
        case .pastelOrange: "#FFB347"
        case .pastelPink: "#DEA5A4"
        case .pastelPurple: "#B39EB5"
        case .pastelRed: "#FF6961"
        case .pastelViolet: "#CB99C9"
        case .pastelYellow: "#FDFD96"
        case .patriarch: "#800080"
        case .payneSGrey: "#536878"
        case .peach: "#FFE5B4"
        case .peachCrayola: "#FFCBA4"
        case .peachOrange: "#FFCC99"
        case .peachPuff: "#FFDAB9"
        case .peachYellow: "#FADFAD"
        case .pear: "#D1E231"
        case .pearl: "#EAE0C8"
        case .pearlAqua: "#88D8C0"
        case .pearlyPurple: "#B768A2"
        case .peridot: "#E6E200"
        case .periwinkle: "#CCCCFF"
        case .persianBlue: "#1C39BB"
        case .persianGreen: "#00A693"
        case .persianIndigo: "#32127A"
        case .persianOrange: "#D99058"
        case .persianPink: "#F77FBE"
        case .persianPlum: "#701C1C"
        case .persianRed: "#CC3333"
        case .persianRose: "#FE28A2"
        case .persimmon: "#EC5800"
        case .peru: "#CD853F"
        case .phlox: "#DF00FF"
        case .phthaloBlue: "#000F89"
        case .phthaloGreen: "#123524"
        case .piggyPink: "#FDDDE6"
        case .pineGreen: "#01796F"
        case .pink: "#FFC0CB"
        case .pinkLace: "#FFDDF4"
        case .pinkOrange: "#FF9966"
        case .pinkPearl: "#E7ACCF"
        case .pinkSherbet: "#F78FA7"
        case .pistachio: "#93C572"
        case .platinum: "#E5E4E2"
        case .plumTraditional: "#8E4585"
        case .plumWeb: "#DDA0DD"
        case .portlandOrange: "#FF5A36"
        case .powderBlueWeb: "#B0E0E6"
        case .princetonOrange: "#FF8F00"
        case .prune: "#701C1C"
        case .prussianBlue: "#003153"
        case .psychedelicPurple: "#DF00FF"
        case .puce: "#CC8899"
        case .pumpkin: "#FF7518"
        case .purpleHeart: "#69359C"
        case .purpleHtmlCss: "#800080"
        case .purpleMountainMajesty: "#9678B6"
        case .purpleMunsell: "#9F00C5"
        case .purplePizzazz: "#FE4EDA"
        case .purpleTaupe: "#50404D"
        case .purpleX11: "#A020F0"
        case .quartz: "#51484F"
        case .rackley: "#5D8AA8"
        case .radicalRed: "#FF355E"
        case .rajah: "#FBAB60"
        case .raspberry: "#E30B5D"
        case .raspberryGlace: "#915F6D"
        case .raspberryPink: "#E25098"
        case .raspberryRose: "#B3446C"
        case .rawUmber: "#826644"
        case .razzleDazzleRose: "#FF33CC"
        case .razzmatazz: "#E3256B"
//        case .red: "#FF0000"
        case .redBrown: "#A52A2A"
        case .redDevil: "#860111"
        case .redMunsell: "#F2003C"
        case .redNcs: "#C40233"
        case .redOrange: "#FF5349"
        case .redPigment: "#ED1C24"
        case .redRyb: "#FE2712"
        case .redViolet: "#C71585"
        case .redwood: "#AB4E52"
        case .regalia: "#522D80"
        case .resolutionBlue: "#002387"
        case .richBlack: "#004040"
        case .richBrilliantLavender: "#F1A7FE"
        case .richCarmine: "#D70040"
        case .richElectricBlue: "#0892D0"
        case .richLavender: "#A76BCF"
        case .richLilac: "#B666D2"
        case .richMaroon: "#B03060"
        case .rifleGreen: "#414833"
        case .robinEggBlue: "#00CCCC"
        case .rose: "#FF007F"
        case .roseBonbon: "#F9429E"
        case .roseEbony: "#674846"
        case .roseGold: "#B76E79"
        case .roseMadder: "#E32636"
        case .rosePink: "#FF66CC"
        case .roseQuartz: "#AA98A9"
        case .roseTaupe: "#905D5D"
        case .roseVale: "#AB4E52"
        case .rosewood: "#65000B"
        case .rossoCorsa: "#D40000"
        case .rosyBrown: "#BC8F8F"
        case .royalAzure: "#0038A8"
        case .royalBlueTraditional: "#002366"
        case .royalBlueWeb: "#4169E1"
        case .royalFuchsia: "#CA2C92"
        case .royalPurple: "#7851A9"
        case .royalYellow: "#FADA5E"
        case .rubineRed: "#D10056"
        case .ruby: "#E0115F"
        case .rubyRed: "#9B111E"
        case .ruddy: "#FF0028"
        case .ruddyBrown: "#BB6528"
        case .ruddyPink: "#E18E96"
        case .rufous: "#A81C07"
        case .russet: "#80461B"
        case .rust: "#B7410E"
        case .rustyRed: "#DA2C43"
        case .sacramentoStateGreen: "#00563F"
        case .saddleBrown: "#8B4513"
        case .safetyOrangeBlazeOrange: "#FF6700"
        case .saffron: "#F4C430"
        case .salmon: "#FF8C69"
        case .salmonPink: "#FF91A4"
        case .sand: "#C2B280"
        case .sandDune: "#967117"
        case .sandstorm: "#ECD540"
        case .sandyBrown: "#F4A460"
        case .sandyTaupe: "#967117"
        case .sangria: "#92000A"
        case .sapGreen: "#507D2A"
        case .sapphire: "#0F52BA"
        case .sapphireBlue: "#0067A5"
        case .satinSheenGold: "#CBA135"
        case .scarlet: "#FF2400"
        case .scarletCrayola: "#FD0E35"
        case .schoolBusYellow: "#FFD800"
        case .screaminGreen: "#76FF7A"
        case .seaBlue: "#006994"
        case .seaGreen: "#2E8B57"
        case .sealBrown: "#321414"
        case .seashell: "#FFF5EE"
        case .selectiveYellow: "#FFBA00"
        case .sepia: "#704214"
        case .shadow: "#8A795D"
        case .shamrockGreen: "#009E60"
        case .shockingPink: "#FC0FC0"
        case .shockingPinkCrayola: "#FF6FFF"
        case .sienna: "#882D17"
//        case .silver: "#C0C0C0"
        case .sinopia: "#CB410B"
        case .skobeloff: "#007474"
        case .skyBlue: "#87CEEB"
        case .skyMagenta: "#CF71AF"
        case .slateBlue: "#6A5ACD"
        case .slateGray: "#708090"
        case .smaltDarkPowderBlue: "#003399"
        case .smokeyTopaz: "#933D41"
        case .smokyBlack: "#100C08"
        case .snow: "#FFFAFA"
        case .spiroDiscoBall: "#0FC0FC"
        case .springBud: "#A7FC00"
        case .springGreen: "#00FF7F"
        case .stPatrickSBlue: "#23297A"
        case .steelBlue: "#4682B4"
        case .stilDeGrainYellow: "#FADA5E"
        case .stizza: "#990000"
        case .stormcloud: "#4F666A"
        case .straw: "#E4D96F"
        case .sunglow: "#FFCC33"
        case .sunset: "#FAD6A5"
        case .tan: "#D2B48C"
        case .tangelo: "#F94D00"
        case .tangerine: "#F28500"
        case .tangerineYellow: "#FFCC00"
        case .tangoPink: "#E4717A"
        case .taupe: "#483C32"
        case .taupeGray: "#8B8589"
        case .teaGreen: "#D0F0C0"
        case .teaRoseOrange: "#F88379"
        case .teaRoseRose: "#F4C2C2"
//        case .teal: "#008080"
        case .tealBlue: "#367588"
        case .tealGreen: "#00827F"
        case .telemagenta: "#CF3476"
        case .tennTawny: "#CD5700"
        case .terraCotta: "#E2725B"
        case .thistle: "#D8BFD8"
        case .thulianPink: "#DE6FA1"
        case .tickleMePink: "#FC89AC"
        case .tiffanyBlue: "#0ABAB5"
        case .tigerSEye: "#E08D3C"
        case .timberwolf: "#DBD7D2"
        case .titaniumYellow: "#EEE600"
        case .tomato: "#FF6347"
        case .toolbox: "#746CC0"
        case .topaz: "#FFC87C"
        case .tractorRed: "#FD0E35"
        case .trolleyGrey: "#808080"
        case .tropicalRainForest: "#00755E"
        case .trueBlue: "#0073CF"
        case .tuftsBlue: "#417DC1"
        case .tumbleweed: "#DEAA88"
        case .turkishRose: "#B57281"
        case .turquoise: "#30D5C8"
        case .turquoiseBlue: "#00FFEF"
        case .turquoiseGreen: "#A0D6B4"
        case .tuscanRed: "#7C4848"
        case .twilightLavender: "#8A496B"
        case .tyrianPurple: "#66023C"
        case .uaBlue: "#0033AA"
        case .uaRed: "#D9004C"
        case .ube: "#8878C3"
        case .uclaBlue: "#536895"
        case .uclaGold: "#FFB300"
        case .ufoGreen: "#3CD070"
        case .ultraPink: "#FF6FFF"
        case .ultramarine: "#120A8F"
        case .ultramarineBlue: "#4166F5"
        case .umber: "#635147"
        case .unbleachedSilk: "#FFDDCA"
        case .unitedNationsBlue: "#5B92E5"
        case .universityOfCaliforniaGold: "#B78727"
        case .unmellowYellow: "#FFFF66"
        case .upForestGreen: "#014421"
        case .upMaroon: "#7B1113"
        case .upsdellRed: "#AE2029"
        case .urobilin: "#E1AD21"
        case .usafaBlue: "#004F98"
        case .uscCardinal: "#990000"
        case .uscGold: "#FFCC00"
        case .utahCrimson: "#D3003F"
        case .vanilla: "#F3E5AB"
        case .vegasGold: "#C5B358"
        case .venetianRed: "#C80815"
        case .verdigris: "#43B3AE"
        case .vermilionCinnabar: "#E34234"
        case .vermilionPlochere: "#D9603B"
        case .veronica: "#A020F0"
        case .violet: "#8F00FF"
        case .violetBlue: "#324AB2"
        case .violetColorWheel: "#7F00FF"
        case .violetRyb: "#8601AF"
        case .violetWeb: "#EE82EE"
        case .viridian: "#40826D"
        case .vividAuburn: "#922724"
        case .vividBurgundy: "#9F1D35"
        case .vividCerise: "#DA1D81"
        case .vividTangerine: "#FFA089"
        case .vividViolet: "#9F00FF"
        case .warmBlack: "#004242"
        case .waterspout: "#A4F4F9"
        case .wenge: "#645452"
        case .wheat: "#F5DEB3"
//        case .white: "#FFFFFF"
        case .whiteSmoke: "#F5F5F5"
        case .wildBlueYonder: "#A2ADD0"
        case .wildStrawberry: "#FF43A4"
        case .wildWatermelon: "#FC6C85"
        case .wine: "#722F37"
        case .wineDregs: "#673147"
        case .wisteria: "#C9A0DC"
        case .woodBrown: "#C19A6B"
        case .xanadu: "#738678"
        case .yaleBlue: "#0F4D92"
//        case .yellow: "#FFFF00"
        case .yellowGreen: "#9ACD32"
        case .yellowMunsell: "#EFCC00"
        case .yellowNcs: "#FFD300"
        case .yellowOrange: "#FFAE42"
        case .yellowProcess: "#FFEF00"
        case .yellowRyb: "#FEFE33"
        case .zaffre: "#0014A8"
        case .zinnwalditeBrown: "#2C1608"
        }
    }
}









